# Generated by Django 2.0 on 2017-12-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('profession', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_pic', models.ImageField(blank=True, default='Rider/prof_pic/prof_pic.png', upload_to='Rider/prof_pic')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Female', 'female'), ('Male', 'male'), ('Both', 'both'), ('None', 'non-specified')], default='None', max_length=30)),
                ('general_location', models.CharField(blank=True, max_length=255)),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collabstudio.Creator')),
            ],
        ),
    ]
